# Automatically generated build file. Do not edit.
COMPONENT_INCLUDES += $(PROJECT_PATH)/SWEMS $(PROJECT_PATH)/SWEMS/include
COMPONENT_LDFLAGS +=  -L$(BUILD_DIR_BASE)/SWEMS -lSWEMS 
COMPONENT_LINKER_DEPS += 
COMPONENT_SUBMODULES += 
COMPONENT_LIBRARIES += SWEMS
component-SWEMS-build: 
